// web/src/widgets/History.jsx
'use strict'
/********************************************************************
 created:    2023-03-02
 author:     lixianmin

 Copyright (C) - All Rights Reserved
 *********************************************************************/
import {useHistoryStore} from "../code/use_history_store";
import {For} from "solid-js";

export default function History() {
    const historyStore = useHistoryStore()
    return <>
        <b>历史命令列表：</b> <br/> count: &nbsp; {historyStore.getHistoryCount()}
        <ol>
            <For each={historyStore.getHistoryList()}>{
                history =>
                    <li>{history}</li>
            }</For>
        </ol>
        <br/>
    </>
}

// web/src/components/History.vue
<template>
  <b>历史命令列表：</b> <br/> count: &nbsp; {{ count }}
  <ol id="history-with-index">
    <li v-for="history in histories" :key="history">
      {{ history }}
    </li>
  </ol>
  <br>
</template>

<script setup>
import {onMounted, toRaw} from "vue"
import {useHistoryStore} from "@/code/use_history_store.js"
import {scrollMainPanelToBottom} from "@/code/main_panel.js"

const historyStore = useHistoryStore()
// 把所有的数据都复制一份, 这是为了防止history的数据变化的时候, 这边再收到通知
const histories = toRaw(historyStore.getHistoryList())
const count = historyStore.getHistoryCount()

onMounted(() => {
  scrollMainPanelToBottom()
})

</script>
